---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-15.04
  - name: debian-8.2
  - name: centos-6.7
  # future...
  # - name: gentoo
  # - name: arch-linux
  # - name: vine-linux-6.3
  # - name: coreos
  # - name: fedora
  # - name: freebsd

suites:
  - name: default
    data_bags_path: test/data_bags
    encrypted_data_bag_secret_key_path: ./data_bag_key

    run_list:
      - recipe[chef-client::config]
      - recipe[chef-client]
      - recipe[base]
      # - recipe[openssh] # ssh config is not needed in test kitchen, I thought.
      - recipe[webapps::default]

    attributes:
      openssh:
        server:
          password_authentication: "no"
          port: 20642
          permit_root_login: "no"

