---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.10
  - name: debian-7.8
  - name: centos-6.6
  # future...
  # - name: gentoo
  # - name: arch-linux
  # - name: vine-linux-6.3
  # - name: coreos
  # - name: fedora
  # - name: freebsd

suites:
  - name: default
    data_bags_path: test/data_bags
    encrypted_data_bag_secret_key_path: ./data_bag_key    

    run_list:
      - recipe[base]
      # - recipe[openssh] # ssh config is not needed in test kitchen, I thought.
      - recipe[webapps::default]

    attributes:
      openssh: 
        server:
          password_authentication: "no"
          port: 20642
          permit_root_login: "no"
