---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.10
  - name: centos-6.6

suites:
  - name: default

    run_list:
      - recipe[base]
      # - recipe[openssh] # ssh config is not needed in test kitchen, I thought.
      - recipe[webapps::default]

    attributes:
      openssh: 
        server:
          password_authentication: "no"
          port: 20642
          permit_root_login: "no"

